- name: step 1 task
  hosts: all
  tasks:
    - name: step 1 run
      tags:
        - step1
      command: sh -f /tmp/toto && echo '{{ test_var1 }}' && sleep 600 || echo 'step 1 KO'
      register: step_1

    - name: step 1 output
      debug:
        var: step_1
