- name: step 1 task
  hosts: all
  tasks:
    - name: step 1 run
      tags:
        - step1
      command: sh -f /tmp/toto && echo '{{ test_var1 }}' || echo 'step 1 KO'
      register: step_1

    - name: myloop
      command: sh -c "while sh ! -f /tmp/tata; do ps auxfwww; done"
      register: myloop_1

    - name: step 1 output
      debug:
        var: step_1
